# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:
    env:
      CI: false
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      working-directory: ./labelpt/web
      run: npm install
    - name: unit test
      working-directory: ./labelpt/web
      run: npm run test
    - name: type check
      working-directory: ./labelpt/web
      run: npm run type-check
    - name: build test
      working-directory: ./labelpt/web
      run: npm run dev-build
